### ISSUE TITLE
[Editor] HTTP source gives an error for setting map type to anything other than json 

### ISSUE THREAD

**Issue by vithusiva** [wso2/carbon-analytics#1856] opened 2020-05-05 05:32 UTC
**Description:**
http source gives an error for setting map type to anything other than json

**Comment by lasanthaS** [comment] 2022-03-02 12:27
Hi @vithusiva, 

We tried to reproduce this issue using the following Siddhi app, but couldn't reproduce it. Therefore we are closing this issue. If you are experiencing the issue still, please re-open with the tested Siddhi app.

**Closed by lasanthaS** 2022-03-02 12:27 UTC
Labels: Severity/Major, Editor
