### ISSUE TITLE
Business rules view page needs a back button

### ISSUE THREAD

**Issue by erangatl** [wso2/carbon-analytics#1196] opened 2018-03-15 17:20 UTC
**Description:**
Business rules view page needs a back button to the list view

**Suggested Labels:**
Business rules manager, Bug

**Suggested Assignees:**
@senthuran16 

**Steps to reproduce:**
Create a business rule, 
Click on the eye to view

**Comment by Niveathika92** [comment] 2018-12-21 09:52
Closing as this is a duplicate of https://github.com/wso2/carbon-analytics/issues/1347

**Closed by Niveathika92** 2018-12-21 09:52 UTC
Labels: Type/Improvement
